### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by Neo23x0**
please add a license so that other users know how they are allowed to use the rules

### CODE REVIEW

**Comment by MalGamy** [comment]
ok, sir... sorry i forget that but i will add it into all rules

**Comment by MalGamy** [comment]
"I edited them. Thank you very much

**Comment by Neo23x0** [comment]
You should still merge this pull request to define the license for the repository.

**Comment by MalGamy** [comment]
ok, i did it

**Pull request merged**
